version: 2
jobs:
  release:
    docker:
      - image: circleci/node:8
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: release
          command: |
            docker build -t insighticon/icon-docker-ci .
            npm run semantic-release

workflows:
  version: 2
  pipeline:
    jobs:
      - release:
          filters:
            branches:
              only: master